name: 'Run SSH4Me'
on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SSH4Me Action
        uses: root
        env:
          AUTH_TOKEN: ${{ 1msFOAezxYgaeXrAcoUK6ssfew4_4LT6p5JT9DhaQ48amoVQW }}
          PASSWORD: ${{ sudipto2001 }}
